import "@/app/globals.css";
import { SkeletonProvider } from "@/components/Layout/SkeletonProvider";
import { SWRProvider } from "@/components/Layout/swrProvider";

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

interface RootLayoutProps {
	children: React.ReactNode;
	params: {
		lang: string;
	};
}

export default function RootLayout({
	children,
	params: { lang },
}: RootLayoutProps) {
	return (
		<html lang={lang}>
			<body className="bg-slate-50 text-zinc-700 dark:bg-zinc-950">
				<SWRProvider>
					<SkeletonProvider>{children}</SkeletonProvider>
				</SWRProvider>
			</body>
		</html>
	);
}
