import { SkeletonProvider } from "@/components/Layout/SkeletonProvider";
import { SWRProvider } from "@/components/Layout/swrProvider";
import "./globals.css";

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="ko">
			<body className="bg-slate-50 text-zinc-700 dark:bg-zinc-950">
				<SWRProvider>
					<SkeletonProvider>{children}</SkeletonProvider>
				</SWRProvider>
			</body>
		</html>
	);
}
